# Deployment da aplicação web conversao-temperatura
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webct
spec:
  selector:
    matchLabels:
      app: webct
  template:
    metadata:
      labels:
        app: webct
    spec:
      containers:
      - name: webct
        image: lcds0807/conversao-temperatura:v2
        ports:
        - containerPort: 5000
---
# Service da aplicação
apiVersion: v1 
kind: Service 
metadata:
  name: webct 
spec: 
  selector:
    app: webct 
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
  type: LoadBalancer       
